// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/roomandfacility": {
    params: {};
  };
  "/gallery": {
    params: {};
  };
  "/reserve": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/roomandfacility" | "/gallery" | "/reserve";
  };
  "App.tsx": {
    id: "App";
    page: "/" | "/about" | "/roomandfacility" | "/gallery" | "/reserve";
  };
  "routes/about.tsx": {
    id: "home";
    page: "/";
  } | {
    id: "about";
    page: "/about";
  };
  "routes/roomandfacility.tsx": {
    id: "roomandfacility";
    page: "/roomandfacility";
  };
  "routes/gallery.tsx": {
    id: "gallery";
    page: "/gallery";
  };
  "routes/reserve.tsx": {
    id: "reserve";
    page: "/reserve";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "App": typeof import("./src/App.tsx");
  "home": typeof import("./src/routes/about.tsx");
  "about": typeof import("./src/routes/about.tsx");
  "roomandfacility": typeof import("./src/routes/roomandfacility.tsx");
  "gallery": typeof import("./src/routes/gallery.tsx");
  "reserve": typeof import("./src/routes/reserve.tsx");
};