// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/roomandfacility": {
    params: {};
  };
  "/gallery": {
    params: {};
  };
  "/reserve": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/roomandfacility" | "/gallery" | "/reserve";
  };
  "App.tsx": {
    id: "home";
    page: "/";
  } | {
    id: "about";
    page: "/about";
  } | {
    id: "roomandfacility";
    page: "/roomandfacility";
  } | {
    id: "gallery";
    page: "/gallery";
  } | {
    id: "reserve";
    page: "/reserve";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "home": typeof import("./src/App.tsx");
  "about": typeof import("./src/App.tsx");
  "roomandfacility": typeof import("./src/App.tsx");
  "gallery": typeof import("./src/App.tsx");
  "reserve": typeof import("./src/App.tsx");
};